# Generated by Django 5.1.1 on 2024-10-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('idquestionario', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.CharField(max_length=255)),
                ('alternativas', models.CharField(max_length=255)),
                ('respostas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('idslide', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('arquivo_pdf', models.FileField(upload_to='slides/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idvideo', models.AutoField(primary_key=True, serialize=False)),
                ('duracao', models.TimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo_video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('tempoDuracao', models.TimeField()),
                ('idarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('idquestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('idmaquina', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMaquina', models.CharField(max_length=100)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adm', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('duracao', models.TimeField()),
                ('idslide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.slide')),
                ('idvideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
