# Generated by Django 5.1.1 on 2024-10-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_idmaquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='idcurso',
        ),
    ]
