# Generated by Django 5.1.1 on 2024-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_maquina_idcurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idmaquina',
        ),
        migrations.AddField(
            model_name='user',
            name='maquinas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='api.maquina'),
        ),
    ]
