# Generated by Django 5.1.1 on 2024-10-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_alternativas_questionario_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('idpergunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='api.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('idalternativa', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('is_correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='api.pergunta')),
            ],
        ),
    ]
