# Generated by Django 5.1.1 on 2024-10-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pergunta_alternativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tempoDuracao',
        ),
        migrations.AddField(
            model_name='curso',
            name='dataCriacao',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maquina'),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
