# Generated by Django 5.1.1 on 2024-10-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_curso_tempoduracao_curso_datacriacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maquina'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
