# Generated by Django 5.1.1 on 2024-10-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_curso_maquina_alter_curso_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='paginas',
        ),
        migrations.RemoveField(
            model_name='video',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duracao',
        ),
        migrations.AddField(
            model_name='aula',
            name='idcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='idslide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.slide'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='idvideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.video'),
        ),
    ]
