# Generated by Django 5.1.1 on 2024-10-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_slide_descricao_remove_slide_paginas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso'),
        ),
    ]
