# Generated by Django 5.1.1 on 2024-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_aula_idcurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='maquina',
        ),
        migrations.AddField(
            model_name='curso',
            name='maquina',
            field=models.ManyToManyField(to='api.maquina'),
        ),
    ]
