# Generated by Django 5.1.1 on 2024-11-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_aula_idcurso_alter_curso_idarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='senha',
            new_name='password',
        ),
    ]
