# Generated by Django 5.1.1 on 2024-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aulausuario_cursousuario_maquinausuarioprogresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('maquinas', models.ManyToManyField(related_name='areas_rel', to='api.maquinarel')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('maquinas', models.ManyToManyField(related_name='usuarios_rel', to='api.maquinarel')),
            ],
        ),
        migrations.AddField(
            model_name='maquinarel',
            name='usuarios',
            field=models.ManyToManyField(related_name='maquina_rel', to='api.usuariorel'),
        ),
        migrations.CreateModel(
            name='CursoRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('usuarios', models.ManyToManyField(related_name='cursos_rel', to='api.usuariorel')),
            ],
        ),
    ]
